version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-bookshop-api
    environment:
      SA_PASSWORD: Your_password123
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - bookshop-api-net

volumes:
  sqlserverdata:

networks:
  bookshop-api-net: